# 应用全局配置
application:
  name: 消息通知API测试服务
  version: 4.0.0

# 本应用的参数配置

# spring 环境配置
spring:
  main:
    allow-bean-definition-overriding: true
  redis: # redis 缓存参数配置
    host: 10.4.208.132
    port: 6379
    password: ZmkDbgaua3Rso33T
    database: 0